title: Project
tabs:
  infos:
    label: Infos
    icon: text
    columns:
      - width: 3/4
        sections:
          infos:
            type: fields
            fields:
              credit:
                label: Credit
                type: text
                width: 1/2
              subtitle:
                label: Subtitle
                type: text
                width: 1/2
              text:
                label: Description
                type: textarea
                size: medium
                buttons:
                  - link
                  - email
      - width: 1/4
        sections:
          thumbnail:
            type: fields
            fields:
              autoid:
                type: hidden
                translate: false
              featured:
                label: Featured image
                type: files
                multiple: false
                query: page.files.template('image')
                uploads: image
              featuredVideo:
                label: Featured video
                type: pages
                multiple: false
                layout: list
                query: site.find('vimeo').children
                image:
                  cover: false
                  ratio: 3/2
                  back: black
                  query: page.cover.toFile
  content:
    extends: sections/blocks
  files:
    icon: file
    sections:
      files:
        type: files
        layout: list
        template: file
      images:
        type: files
        layout: cards
        template: image
        size: tiny
